Poison arrow refactor, mortar and pestle crafting
Blackstone-SS13/BLACKSTONE pull request #1086
Opened 2024-05-29 06:23 UTC by DerFlammenwerfer

## About The Pull Request
It is my understanding that the reason poison arrows were commented out is because the poison code was done in such a way that they did not respect armor or shields whatsoever. After testing two different methods, I have successfully coded them so that they will not apply poison if they are deflected (such as by a shield or breastplate) or if one's overall armor is sturdy enough that no brute damage is dealt on impact. I have also made it so that, after ten seconds of hitting a simple mob, the mob will take 100 toxin damage, potentially killing it after the delay. Additionally, whether poison is applied or not, if the arrow is recoverable it will be an un-poisoned arrow of the same type, allowing you to reuse it later.

Mortars and pestles can now be crafted from small stones, which might become useful in future alchemical coding. Mortars cannot pour or drain liquids themselves, but can be filled or drained by other containers with those capabilities. This allows players to extract the poison from poison jacksberries for use in crafting poison arrows. A single arrow is enough to send someone into critical condition in around 40 seconds, but this can be prevented by applying a leech in the 20 seconds or so before you begin puking, and/or by drinking water, which will now heal poisoning at -1 per life tick; half the rate of a leech. These methods together are enough to neutralize the poison damage, but can exacerbate an un-pressured, bleeding wound.

## Why It's Good For The Game
Woe, poisoners be upon ye. This re-implements and re-factors an arrow type that had to be removed because it wouldn't respect armor, as well as a couple of vital alchemical tools (mortar and pestle) that can tie into future medicinal and alchemical mechanics. The arrow is quite dangerous, but easy enough to counter with either a bit of medical prep, standing behind a palisade, blocking with a shield, or by wearing plated or scale armor, as anything that blocks the damage altogether will prevent poisoning. It is also useful for roguish sorts who want to try and capture others for RP reasons, but require more investment for fraggers to get their hands on, as the mortar and pestle have a crafting difficulty of 3, farming berries is difficult without a sickle, and discerning which berries are poison does require a taste-test, after all.

2024-05-29 06:49 UTC, ChungusGamer666 requested changes
oof

2024-05-29 06:49 UTC, ChungusGamer666 commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		M.adjustToxLoss(100) //Very useful for hunters who want to conserve ammo
dont call sleep here, this should return immediately
use a timer

2024-05-29 06:49 UTC, ChungusGamer666 commented on code/modules/mob/living/living_defense.dm
> +					M.show_message("<span class='danger'>You feel an intense [A.poisonfeel] sensation spreading swiftly from the area!</span>") //A warning seems only fair, this poison can potentially down someone
snowflake code, there has to be a better way, maybe a new proc for base /obj/projectile

2024-05-29 06:49 UTC, ChungusGamer666 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		M.adjustToxLoss(-1)
Water should not heal toxin damage, sleep should heal toxin damage if it doesn't already

2024-05-29 11:47 UTC, CVSthePharmacy commented
give the men at arms a mortar so they can bomb church

2024-05-29 16:33 UTC, DerFlammenwerfer commented on code/modules/mob/living/living_defense.dm
> +					M.show_message("<span class='danger'>You feel an intense [A.poisonfeel] sensation spreading swiftly from the area!</span>") //A warning seems only fair, this poison can potentially down someone
The better way would be to add the three poison vars specific to the poison arrow to the base projectile and change it to check if they aren't null. I can do that easily enough.

2024-05-29 16:42 UTC, DerFlammenwerfer commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		M.adjustToxLoss(-1)
Yes biologically, it should. Water is what the body uses to dilute and expel toxins. One of the processes of the human body to remove toxins is for the kidneys to filter them out into urine via the kidneys. You need to drink water to keep this process going, so it makes sense for water to help flush toxins already absorbed in the blood. Water is life

Source: https://vetmed.tamu.edu/peer/detoxification/

2024-05-29 16:55 UTC, DerFlammenwerfer commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		M.adjustToxLoss(100) //Very useful for hunters who want to conserve ammo
`addtimer(CALLBACK(src, PROC_REF(adjustToxinLoss), 100), 20)`
Would this work better?

2024-05-29 17:14 UTC, DerFlammenwerfer commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		M.adjustToxLoss(100) //Very useful for hunters who want to conserve ammo
`addtimer(CALLBACK(M, TYPE_PROC_REF(/mob/living, adjustToxLoss), 100), 10 SECONDS)`
After some fiddling with it, I believe this will work.

2024-05-29 17:37 UTC, DerFlammenwerfer commented on code/modules/mob/living/living_defense.dm
> +					M.show_message("<span class='danger'>You feel an intense [A.poisonfeel] sensation spreading swiftly from the area!</span>") //A warning seems only fair, this poison can potentially down someone
Alright, I've added the poison vars I used for the poison arrows to the base projectile instead, leaving them null by default. This adds support for projectile spells/mobs to use this system as well.

2024-05-29 18:17 UTC, DerFlammenwerfer commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		M.adjustToxLoss(100) //Very useful for hunters who want to conserve ammo
I've tested it, and it works. I'm going to add a visible message for the simplemob effect so that players have feedback on when the timer has gone off.

2024-05-29 18:18 UTC, DerFlammenwerfer commented on code/modules/mob/living/living_defense.dm
> +					M.show_message("<span class='danger'>You feel an intense [A.poisonfeel] sensation spreading swiftly from the area!</span>") //A warning seems only fair, this poison can potentially down someone
Testing confirms the new method works. It's been committed now, thanks for the suggestion.

2024-05-29 18:58 UTC, DerFlammenwerfer commented
I have added a second timer, since I can't fire two procs with the same one, to display a visible message when the bonus damage is applied to the mob.

https://i.imgur.com/vVppAit.png

2024-05-29 19:27 UTC, SELFHELL commented
Cool as hell change, actually doing poison arrows in a non-slopcode way.

2024-05-29 20:45 UTC, DerFlammenwerfer commented
> Cool as hell change, actually doing poison arrows in a non-slopcode way.

Appreciate the vote of confidence, but I'm not 100% happy with the mortar and pestle; I couldn't really figure out what was stopping the mortar from being able to use the same intents as other containers directly, and I feel like leaving out those intents is a little sloppy.

2024-05-30 08:39 UTC, DerFlammenwerfer commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		M.adjustToxLoss(-1)
Tox healing has been removed from the PR. May Pestra have mercy on your souls.

2024-05-31 01:30 UTC, BlueMemesauce commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		addtimer(CALLBACK(M, TYPE_PROC_REF(/mob/living, adjustToxLoss), 100), 10 SECONDS)
```suggestion
		cant we make it add reagent instead? that would be cooler than just applying 100 tox loss after 10 seconds
```

2024-05-31 01:31 UTC, BlueMemesauce commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		addtimer(CALLBACK(M, TYPE_PROC_REF(/mob/living, adjustToxLoss), 100), 10 SECONDS)
oh nvm this is for simple animals

2024-05-31 01:32 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	possible_item_intents = list(INTENT_GENERIC)
```suggestion
	why is this generic
```

2024-05-31 01:38 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(istype(I ,/obj/item/reagent_containers/glass))
```suggestion
	this shit should all already be in the parent???? why are you copy pasting thing
```

2024-05-31 01:39 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(istype(I ,/obj/item/reagent_containers/glass))
this is even stranger because you're adding the pouring behavior for other items to attackby
even though they already have that behavior when they attack obj

2024-05-31 03:50 UTC, DerFlammenwerfer commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		addtimer(CALLBACK(M, TYPE_PROC_REF(/mob/living, adjustToxLoss), 100), 10 SECONDS)
> oh nvm this is for simple animals

If simple mobs processed reagents, yeah I could. Unfortunately not the case.

2024-05-31 03:53 UTC, DerFlammenwerfer commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(istype(I ,/obj/item/reagent_containers/glass))
> this is even stranger because you're adding the pouring behavior for other items to attackby even though they already have that behavior when they attack obj

Because the mortar's default attackby() proc overwrites the normal pour/fill intents, and even when I add those same intents to the mortar, they do not work; it ignores them.

So to answer your question, I'm doing it this way because it actually works.

2024-05-31 03:54 UTC, DerFlammenwerfer commented on code/modules/reagents/reagent_containers/glass.dm
> +	possible_item_intents = list(INTENT_GENERIC)
I attempted this already, and it does not work.

2024-05-31 05:50 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	..()
?????whats the point of this it does nothing

2024-05-31 05:56 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(istype(I ,/obj/item/reagent_containers/glass))
pour/fill intents are for attack obj, attacking an object. Which isn't overwritten you just did ..()

2024-05-31 06:03 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	possible_item_intents = list(INTENT_GENERIC)
Then why even make this a reagent_container/glass?

2024-05-31 06:37 UTC, BlueMemesauce commented on code/modules/reagents/reagent_containers/glass.dm
> +	..()
```	
if(user.used_intent.type == INTENT_GENERIC)
		return ..()
	if(grinded)
		to_chat(user, "<span class='warning'>There is something inside!</span>")
		return
```

2024-05-31 09:10 UTC, ChungusGamer666 commented
looks ok now

2024-05-31 13:21 UTC, CVSthePharmacy commented
Cmon give the castle guards an actual mortar to bomb the vamp manor

2024-06-01 00:34 UTC, DerFlammenwerfer commented on code/modules/reagents/reagent_containers/glass.dm
> +	possible_item_intents = list(INTENT_GENERIC)
> Then why even make this a reagent_container/glass?

I didn't; it was already coded as such.

2024-06-01 00:36 UTC, DerFlammenwerfer commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(istype(I ,/obj/item/reagent_containers/glass))
> I guess that makes sense since you need a way to block the pouring if there is something inside but isn't there a way to just return the previously overwritten code so it doesnt have to be copy pasted

If I knew how to do that specifically, I would have done it, but if you have to ask this, then you don't know the answer either.

2024-06-01 00:39 UTC, DerFlammenwerfer commented on code/modules/reagents/reagent_containers/glass.dm
> +	..()
I've removed this proc call

2024-06-01 00:42 UTC, DerFlammenwerfer commented
> Cmon give the castle guards an actual mortar to bomb the vamp manor

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/22332543/4ee370c6-c4f7-4deb-b577-e73c64172f59)

2024-06-01 02:57 UTC, DerFlammenwerfer commented
> looks ok now

Please don't forget to resolve your change request.

2024-06-01 04:00 UTC, BlueMemesauce commented
idk if you can github just does that to annoy people

2024-06-01 22:30 UTC, HaultyAnonie commented on code/game/objects/items/rogueweapons/ranged/ammo.dm
> +		M.show_message("<span class='danger'>You feel an intense burning sensation spreading swiftly from the puncture!</span>") //In case a player is in control of the mob.
Client if-check maybe?

2024-06-01 23:31 UTC, BlueMemesauce commented
wait what if we just stole tgstation syringe gun code

2024-06-02 07:17 UTC, merged