[FIX] No more deposits/withdrawals by "unknowns"
Blackstone-SS13/BLACKSTONE pull request #1160
Opened 2024-06-02 12:45 UTC by Gyrandola

## About The Pull Request

Fixes being able to anonymously deposit or withdraw money from your bank account if your face is covered.

2024-06-02 14:56 UTC, ChungusGamer666 commented on code/controllers/subsystem/rogue/treasury.dm
> +	if(!character) return FALSE
hate let me tell you

2024-06-02 14:57 UTC, ChungusGamer666 requested changes
oy vey

2024-06-02 14:57 UTC, ChungusGamer666 commented on code/controllers/subsystem/rogue/treasury.dm
> +                send_ooc_note("<b>The Bank:</b> Error: Insufficient funds in the player's account to complete the withdrawal.", character = character)
i am almost certain that this is not right, i seriously doubt bank accounts are stored with direct references to a character instead of their name

2024-06-02 15:00 UTC, AlamoTurtle commented
Doesn't the shylock ask for your finger to make an account? Would it not be using that instead of your face? Am I just missing some bug that allows you to make 70 alternative bank accounts?

2024-06-02 15:19 UTC, wgtjunior743 commented
> Doesn't the shylock ask for your finger to make an account? Would it not be using that instead of your face? Am I just missing some bug that allows you to make 70 alternative bank accounts?

you can't make new accounts, but you can make one and later deposit / withdraw as unknown if you use a mask/hood

2024-06-02 15:36 UTC, Gyrandola commented on code/controllers/subsystem/rogue/treasury.dm
> +                send_ooc_note("<b>The Bank:</b> Error: Insufficient funds in the player's account to complete the withdrawal.", character = character)
That might have been changed when someone reported they could access some other guy's account with the same name. Anyways, I used the generate_money_account proc, aka the deposit one, as reference and it seems to work just fine.

2024-06-04 20:55 UTC, ChungusGamer666 requested changes
Direct references to humans stored in the account list will create issues, I double checked the code. Do not mix and match strings with references to instances of human characters, all references should be strings - That is, the real name variable of the character.

2024-11-29 16:23 UTC, closed without merging