You can only behead by attacking neck
Blackstone-SS13/BLACKSTONE pull request #337
Opened 2024-04-23 13:49 UTC by panvxv

## About The Pull Request
Change so players need to go for neck - harder to hit part - to behead someone.

## Why It's Good For The Game
Beheading was too easy and required little weapon skill and stats.

2024-04-23 15:50 UTC, CVSthePharmacy commented
if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill

2024-04-23 16:27 UTC, TheManWithNoHands commented
> if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill

Yeah but you can counter axe to the head by a helmet. Just as you can counter beheading by sword with neckguard with this.
Maces are already meta for people that know what they are doing. You can knock someone out for like 15 seconds if you hit their head from behind. Or just onehit kill em even with a helmet on. Cutting someones head off as top combat strategy is too cheesy. A rock paper siccors thing is healthier.

2024-04-23 16:45 UTC, Gyrandola commented
> > if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill
> 
> Yeah but you can counter axe to the head by a helmet. Just as you can counter beheading by sword with neckguard with this. Maces are already meta for people that know what they are doing. You can knock someone out for like 15 seconds if you hit their head from behind. Or just onehit kill em even with a helmet on. Cutting someones head off as top combat strategy is too cheesy. A rock paper siccors thing is healthier.

arent swords still worse than maces this way though.

2024-04-23 17:12 UTC, Wintermote commented
I don't think this is a good solution to the problem

Instead, I think attacks on the head need to have a wildly lower chance to hit unless someone is laying prone, and a higher chance if they are prone + immobilized. So that aiming for the head instead of chest is a very risky move in a fight, rather than what everyone does. 

That would also help the problem with mace stuns.

2024-04-23 17:21 UTC, panvxv commented
> if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill

axes actually don't have insta kill on head hit, swords have as stab crit to the face insta kill.

2024-04-23 17:35 UTC, CVSthePharmacy commented
> > if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill
> 
> axes actually don't have insta kill on head hit, swords have as stab crit to the face insta kill.

wdym, to the eyes or nose?

2024-04-23 17:36 UTC, CVSthePharmacy commented
> > if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill
> 
> axes actually don't have insta kill on head hit, swords have as stab crit to the face insta kill.

axes have embed chance that instakill

2024-04-23 17:40 UTC, panvxv commented
> > > if you do this then axes and maces will be the new meta, as axes can embed in heads for an instakill
> > 
> > 
> > axes actually don't have insta kill on head hit, swords have as stab crit to the face insta kill.
> 
> axes have embed chance that instakill

only on chest, not on head

2024-04-23 17:42 UTC, CVSthePharmacy commented
and on head

2024-04-23 18:15 UTC, TheManWithNoHands commented
> arent swords still worse than maces this way though.

That maces dont have a counter really, is a diffrent problem.

2024-04-23 19:17 UTC, bobjension commented
godly PR

2024-04-23 21:34 UTC, ChungusGamer666 commented
Godly pr

2024-04-23 21:36 UTC, ChungusGamer666 requested changes

2024-04-23 21:36 UTC, ChungusGamer666 commented on code/modules/surgery/bodyparts/dismemberment.dm
> +			return FALSE
This check is absolutely insane. DO NOT DO THIS, dismemberable is called that for a reason.

Add another if check instead below this, if(body_zone == BODY_ZONE_HEAD && (zone_precise != BODY_ZONE_PRECISE_NECK)) return FALSE

2024-04-23 22:29 UTC, merged

2024-04-24 18:43 UTC, Wintermote commented
There is a bug (already mentioned in discord) with the guillotine, which appears to be doing head damage instead of neck damage and as such will never actually decapitate anyone.

2024-04-25 14:10 UTC, CVSthePharmacy commented
> > arent swords still worse than maces this way though.
> 
> That maces dont have a counter really, is a diffrent problem. Problem with decaps, they are rather easy to do. And they perma kill you. Any other way you die and you can be revived. As long as the head stays on. And to be perma killed from a oneshot from 100% to 0 health, is something that only can cause frustration in the beheaded in question. So macking it so, that you actually need to hit the neck, to cut through the neck, is kinda good.

ok but you see the thing is blackstone combat is quite something, you cannot die via getting maced in the chest, you can have a morbillion brute damage and not die, it's only critical hits to the head with a mace that get you