Bailiff additions and sheriff changes
Blackstone-SS13/BLACKSTONE pull request #410
Opened 2024-04-27 13:51 UTC by K4rlox

## About The Pull Request

Changes Sheriffs description to clarify his role, and adds in two new Jobs; Bailiff and his assistants Councillors.

## Why It's Good For The Game
While k4rl may be submitting the PR for this, Headmin (Boardsofcanada) wrote the Descriptions, Composed the clothing, and requested for this to be done for me since I don't have any skills or experience in Git or scripting. This change in general is much more accurate to the setting, and breathes a new noble into the Manor's life cycle. This also cuts the sheriff off of some of his duties, while giving him new ones and giving a whole new role to assist the King and People in their activities.

2024-04-27 14:00 UTC, ChungusGamer666 requested changes
These jobs feel awfully bloaty and pointless but before we discuss that, do the requested changes

2024-04-27 14:00 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
> +	flag = SHERIFF
wrong flag

2024-04-27 14:00 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/nobility/councillor.dm
> +	department_flag = NOBLEMEN
no job flag?

2024-04-27 14:54 UTC, K4rlox commented on code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
> +	flag = SHERIFF
some other jobs including the hand use the shreiff flag

2024-04-27 14:55 UTC, K4rlox commented
> These jobs feel awfully bloaty and pointless but before we discuss that, do the requested changes

DM boards_of_canada for that
despite i made the PR, its not really my PR
it was a direct addition request from the headmin, they were the ones who made the jobs

2024-04-27 14:56 UTC, K4rlox commented on code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
> +	flag = SHERIFF
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/118483925/d94aff7d-fd6e-4729-bcb7-1866ee0d0afb)

2024-04-27 14:58 UTC, K4rlox commented on code/modules/jobs/job_types/roguetown/nobility/councillor.dm
> +	department_flag = NOBLEMEN
added, also fixed keyring

2024-04-27 16:28 UTC, OrbitalParadise commented
usually the king handles whatever dispute there is, feels like a nerf to that if the guards just bring them to the court instead. Maybe make this into a courtroom for witch hunters

2024-04-27 17:57 UTC, K4rlox commented
> usually the king handles whatever dispute there is, feels like a nerf to that if the guards just bring them to the court instead. Maybe make this into a courtroom for witch hunters

not the right person to tell this buddy

2024-04-27 18:54 UTC, YosemiteYam commented
This is such a pointless PR and introduces more rolebloat and needlessly divides the crown faction. The sheriff is THE military head and enforces the law, the king SETS the law and if he wants to he can preside over judgement. We don't need a specific judge role with guards for that, and we don't need to nerf the sheriff's role either. We already have one role (dungeonkeeper) that is not used enough because people don't bring in prisoners, we don't need bailiff/counciller roles too. Also these descriptions are so bad, iterating that one is noble while the sheriff is not = unnecessary and creates discord. Seems to me that the judge role is for people who failed to roll king and just want to larp as King-Lite. 

The sheriff is the head of military (head of security) role and a minor noble, the king is the captain/lawgiver/judge role, we don't need to complicate this any more and make the crown more dysfunctional than it already is by giving a whole sub-faction of law-men when people barely get "judged" since there's no point to. The most common crimes are pickpocketing and assault and we have a whole garrison, sheriff, dungeonkeeper and a king to figure out anything more complex than that (never happens)

I hope the maintainers don't allow this

2024-04-27 19:26 UTC, K4rlox commented
> This is such a pointless PR and introduces more rolebloat and needlessly divides the crown faction. The sheriff is THE military head and enforces the law, the king SETS the law and if he wants to he can preside over judgement. We don't need a specific judge role with his own (useless and role bloat) assistants for that, and we don't need to nerf the sheriff's role either. We already have one role (dungeonkeeper) that is not used enough because people don't bring in prisoners, we don't need bailiff/counciller roles too. Also these descriptions are so bad, iterating that one is noble while the sheriff is not = unnecessary and creates discord. Seems to me that the bailiff/judge role is for people who failed to roll king and just want to larp as King-Lite. If the king in a round wants to set specific councillors to preside over the maybe one criminal case that isn't some beggar twisting peoples dicks instead of doing it himself, he can appoint some or literally just use his hand, who most of the time doesn't have shit to do anyway.
> 
> The sheriff is the head of military (head of security) role and a minor noble, the king is the captain/lawgiver/judge role, we don't need to complicate this any more and make the crown more dysfunctional than it already is by giving a whole sub-faction of law-men when people barely get "judged" since there's no point to. The most common crimes are pickpocketing and assault and we have a whole garrison, sheriff, dungeonkeeper and a king to figure out anything more complex than that (never happens).
> 
> This is supposed to be a backwater kingdom where the law is direct and brutal, served by the King's goons or in rare cases the king himself, a law bureaucracy that will turn every beggar pickpocker case into a thirty minute court session is the silliest thing I can imagine for this server.
> 
> I hope the maintainers don't allow this

it was requested and written by the headmin

2024-04-28 07:30 UTC, ChungusGamer666 commented
Emoney likes this PR, I will give it a try

2024-04-28 11:04 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/sheriff.dm
> +	tutorial = "You either inherited this role or were elected to it, you belong to no nobility and serve the king as loyal as you may, for he has paid you well. Enforce the law and ensure order prevail
Why is the Sheriff not a noble? Isn't that kind of weird?

2024-04-28 11:05 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
> +	"Humen",
Humen, Humen, Aasimar. Might wanna fix this.

2024-04-28 13:15 UTC, K4rlox commented on code/modules/jobs/job_types/roguetown/nobility/sheriff.dm
> +	tutorial = "You either inherited this role or were elected to it, you belong to no nobility and serve the king as loyal as you may, for he has paid you well. Enforce the law and ensure order prevail
ask the headmin

2024-04-28 13:16 UTC, K4rlox commented on code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
> +	"Humen",
fixed

2024-04-29 04:32 UTC, Real-MAGNUM commented
Bailiff mapping is commented under bailiff key. Oops.

2024-04-29 22:21 UTC, Real-MAGNUM commented
Do not merge this PR. I need(want) to do some stupid stuff because I dont want to fight versions of roguetown.dmm that werent converted with mapmerger2. I'll merge it when the conflicts are sorted, I'm ready.

2024-04-30 11:00 UTC, merged