BanditGODS
Blackstone-SS13/BLACKSTONE pull request #490
Opened 2024-05-01 01:00 UTC by bobjension

I love bandits and I'm reopening this because I love bandits

2024-05-01 04:45 UTC, YosemiteYam commented
Bervors...expert polearm skill...bardiches...steel masks..why do bandits start with better everything than a castle guard besides their chest armor..are these bandits funded by NATO

2024-05-01 04:49 UTC, Real-MAGNUM requested changes
Bandits do **not** need 5 in wrestling. All their skills being buffed, on top of bonuses to support the meta weapon loadouts that include crossbows and polearms is a way bigger buff than might seem at first glance. If default skills were gimped and you were given a choice in what you wanted to take, it might be bearable and excusable as "variety" instead of an ungodly buff.

This PR reads as powercreep for a role you play a lot. Try to focus more on adding variety/loadouts to bandits, as opposed to just outright buffing them in every way you can find.

2024-05-01 05:30 UTC, bobjension commented
is this PR biased? yeah it is, adventurers still have 75 slots with infinite respawns, so I feel VERY VERY entitled for them to die as soon as possible, now I'll admit, I DID make the loadouts really fucking good, but I made their slots completely RNG so it's more fun that way, you can get up to a bandit horde with 40 bloodthirsty bastards with gamer gear or 1 little lone bandit, also emoney nerfed them too hard so they're worse adventurers lol, unless adventurers get reduced slots, (I'm not gonna bother opening that can of worms) also, "subclasses" PR looks like it's gonna buff adventurers and guards a little bit.

also they had 5 in wrestling and 4 in unarmed originally, those skills should've never been changed at all.



Also, lore reason why the bandits have good "bandit gear" is because of Giza.

2024-05-01 07:35 UTC, hivemuscle commented
currently all bandits i encountered done nothing but rdm, great skills and equipment will push them only further

bandits lack a way to spend their money - thats a real problem. they can not visit town under normal circumstances because of giant "BANDIT!" text. they also lack a sanity system, which will push them to theft and looting, while punishing for unnecessary deathmatch killings - bandits must remove your money and armor, not you

2024-05-01 08:42 UTC, Real-MAGNUM commented
> currently all bandits i encountered done nothing but rdm, great skills and equipment will push them only further
> 
> bandits lack a way to spend their money - thats a real problem. they can not visit town under normal circumstances because of giant "BANDIT!" text. they also lack a sanity system, which will push them to theft and looting, while punishing for unnecessary deathmatch killings - bandits must remove your money and armor, not you

This is a good point. They're entirely centered around wiping the map instead of doing bandit activities. Once the new bog map is in, they'll have SO much space to exist outside the walls, and a lot more to do out there than walk to the gates for a fight. I actually like bandits more than most other antags, I just think people play them as murderhobos because they see other people do this. A pr buffing them to let them kill more, and kill easier, might just make it that much worse.

2024-05-01 10:13 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			H.mind.adjust_skillrank(/datum/skill/combat/polearms, 4, TRUE)
```suggestion
			H.mind.adjust_skillrank(/datum/skill/combat/polearms, 3, TRUE)
```

2024-05-01 10:14 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			H.mind.adjust_skillrank(/datum/skill/combat/swords, 3, TRUE)
```suggestion
			H.mind.adjust_skillrank(/datum/skill/combat/swords, 2, TRUE)
```

2024-05-01 10:14 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			H.mind.adjust_skillrank(/datum/skill/combat/whipsflails, 3, TRUE)
```suggestion
			H.mind.adjust_skillrank(/datum/skill/combat/whipsflails, 2, TRUE)
```

2024-05-01 10:17 UTC, Real-MAGNUM commented on code/game/gamemodes/roguetown/roguetown.dm
> +		num_bandits = CLAMP(round(num_players() / 2), 1, 40)
Please change this into a weight system. 5 players per bandit spawn, capped at 25.

Otherwise, hard limit of 20 max.

2024-05-01 10:22 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/unarmed, 4, TRUE)
```suggestion
	H.mind.adjust_skillrank(/datum/skill/combat/axesmaces, 2, TRUE)
	H.mind.adjust_skillrank(/datum/skill/combat/wrestling, 2, TRUE)
	H.mind.adjust_skillrank(/datum/skill/combat/unarmed, 2, TRUE)
```

2024-05-01 10:23 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
```suggestion
	H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 1, TRUE)
```

You have a crossbow class that gives 2 to this stat, this is redundant.

2024-05-01 10:27 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			mask = /obj/item/clothing/mask/rogue/facemask/steel
```suggestion
```

2024-05-01 10:28 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			mask = /obj/item/clothing/mask/rogue/facemask/steel
```suggestion
```
Please keep on-spawn ranged classes vulnerable on-spawn.

2024-05-01 10:32 UTC, Real-MAGNUM commented
Essentially, bandits should train-up skills like everyone else, and steal for weapons and armor that are capable of breaking through the gates if that's what they want to do. Round start rushing into the keep to kill everyone they can turns bandits into a very boring antag, when they're designed for freedom and creativity. Buffing them so they're better at killing only makes this problem worse. If you're trying to kill everyone in the server as fast as possible at round start, you might be playing bandits wrong.

2024-05-01 11:09 UTC, Hmeister-real commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			mask = /obj/item/clothing/mask/rogue/facemask/steel
they need something to replace it so they can hide their face without a hood

2024-05-01 13:31 UTC, Real-MAGNUM commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			mask = /obj/item/clothing/mask/rogue/facemask/steel
edited

2024-05-01 15:14 UTC, CVSthePharmacy commented
> Also, lore reason why the bandits have good "bandit gear" is because of Giza.

bandits are from the gaza strip

2024-05-01 15:18 UTC, CVSthePharmacy commented
> Essentially, bandits should train-up skills like everyone else, and steal for weapons and armor that are capable of breaking through the gates if that's what they want to do. Round start rushing into the keep to kill everyone they can turns bandits into a very boring antag, when they're designed for freedom and creativity. Buffing them so they're better at killing only makes this problem worse. If you're trying to kill everyone in the server as fast as possible at round start, you might be playing bandits wrong.

bandits don't have time to train, they are not a build up antag, they are a roundstart antag that is SUPPOSED to spice up the start of the round as everyone scrambles to get set up

2024-05-01 15:19 UTC, CVSthePharmacy commented
they are also not boring, enjoyment is subjective, in other's eyes this is very fun

2024-05-01 15:22 UTC, CVSthePharmacy commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
it isn't, I've actually spawned in before as a crossbow bandit and gotten weak skills.

2024-05-01 15:25 UTC, CVSthePharmacy commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			H.mind.adjust_skillrank(/datum/skill/combat/polearms, 4, TRUE)
keep it at least at 3, but 4 seems pretty balanced for a role that dies roundstart

2024-05-01 15:26 UTC, CVSthePharmacy commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			H.mind.adjust_skillrank(/datum/skill/combat/whipsflails, 3, TRUE)
stop nerfing everything magnum, skilled is good for a role that literally cannot make a training dummy to actually GET to skilled,

2024-05-01 18:06 UTC, hivemuscle commented
> > Essentially, bandits should train-up skills like everyone else, and steal for weapons and armor that are capable of breaking through the gates if that's what they want to do. Round start rushing into the keep to kill everyone they can turns bandits into a very boring antag, when they're designed for freedom and creativity. Buffing them so they're better at killing only makes this problem worse. If you're trying to kill everyone in the server as fast as possible at round start, you might be playing bandits wrong.
> 
> bandits don't have time to train, they are not a build up antag, they are a roundstart antag that is SUPPOSED to spice up the start of the round as everyone scrambles to get set up

the need to train will reduce the desire to suicide rush something, because it's not so cool to lose something that you actually earned. also, rounds last like 3 hours minimum, and to raise skill from average (2) to skilled (3) you need like 10 minutes maximum even with 5 int (comically small amount).

2024-05-01 18:19 UTC, OrbitalParadise commented
> currently all bandits i encountered done nothing but rdm, great skills and equipment will push them only further
> 
> bandits lack a way to spend their money - thats a real problem. they can not visit town under normal circumstances because of giant "BANDIT!" text. they also lack a sanity system, which will push them to theft and looting, while punishing for unnecessary deathmatch killings - bandits must remove your money and armor, not you

Sanity system is too much when there is already barebones stress code. So rn there will be mood, stress, fatigue, and tiredness which is diff then fatigue. I think it's too bloated to add sanity and talk about it when mood isn't even in but I digress.

2024-05-01 19:01 UTC, bobjension commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
it stacks, so a normal bandit spawns with 2 crossbow skill, and a bandit who spawns with the crossbow bandit loadout is gonna get a additional 2+ crossbow skill

2024-05-01 19:04 UTC, bobjension commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			H.mind.adjust_skillrank(/datum/skill/combat/swords, 3, TRUE)
they should atleast expert skill for the weapon they spawn with

2024-05-01 19:06 UTC, bobjension commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			mask = /obj/item/clothing/mask/rogue/facemask/steel
the steel mask only covers the face codewise, and no neck protection roundstart so they're REALLY fucking weak melee wise

2024-05-01 19:08 UTC, bobjension commented on code/game/gamemodes/roguetown/roguetown.dm
> +		num_bandits = CLAMP(round(num_players() / 2), 1, 40)
i'd rather let RNG settle it, gonna people guessing each round how many bandits spawned, I'll decrease it to a max of 35 though

2024-05-01 19:09 UTC, Real-MAGNUM commented
> Sanity system is too much when there is already barebones stress code. So rn there will be mood, stress, fatigue, and tiredness which is diff then fatigue. I think it's too bloated to add sanity and talk about it when mood isn't even in but I digress.

Sanity is a talk for a different place, like a discord forum post. I'm going to push the idea of penalties per kill on death when it happens, so you're only punished for killing other players after death. A longer respawn of some sort. This should stop the valid, but bad faith kill frenzies from players and antags alike.

2024-05-01 19:29 UTC, bobjension commented
this is what a normal coif is
![coif](https://github.com/Blackstone-SS13/BLACKSTONE/assets/76455911/40c0dba9-2545-4008-99da-12cc163b0bfd)

2024-05-01 20:07 UTC, hivemuscle commented
> > Sanity system is too much when there is already barebones stress code. So rn there will be mood, stress, fatigue, and tiredness which is diff then fatigue. I think it's too bloated to add sanity and talk about it when mood isn't even in but I digress.
> 
> Sanity is a talk for a different place, like a discord forum post. I'm going to push the idea of penalties per kill on death when it happens, so you're only punished for killing other players after death. A longer respawn of some sort. This should stop the valid, but bad faith kill frenzies from players and antags alike.

to me low sanity must:
1. lower your stats (int, luc, per)
2. make your eyes pure red (255, 0, 0)
3. make you say dumbass things randomly ("i will fucking murder you!!" while you are speaking to the king lol)
4. cause literal jumpscares on your screen
5. add something like "they are twitching maniacally" to your character description text
6. temporary stun you in a burst of maniacal laughter/scream
7. lead to loss of control over your character, making them an agressive NPC (temporary seizures at first, but if sanity continues to fall - permanent) or even offering your body to a random spirit (tyler durden)

2024-05-01 22:39 UTC, ChungusGamer666 commented
Guy who made this PR got banned

2024-05-01 22:39 UTC, closed without merging

2024-05-01 22:50 UTC, hivemuscle commented
> Guy who made this PR got banned

for what? 1984

2024-05-01 22:59 UTC, K4rlox commented
> > Guy who made this PR got banned
> 
> for what? 1984

threw the entire royal family and royal guard into the acid pit

2024-05-02 15:20 UTC, CVSthePharmacy commented
> Guy who made this PR got banned

that isn't a reason to close the pr, reopen it and merge

2024-05-02 15:23 UTC, ChungusGamer666 commented
> > Guy who made this PR got banned
> 
> that isn't a reason to close the pr, reopen it and merge

Emoney has clearly stated his wishes to me of bandits being around as dumb and inefficient as the bog guards are, this PR wouldn't be merged either way