Total Autoccorect Overhaul
Blackstone-SS13/BLACKSTONE pull request #51
Opened 2024-04-13 10:32 UTC by armorheart

- Added a metric ton of new words
- Organized & Separated the autocorrect list into sets
- Refined existing words
- Removed insensible or irellevant words

2024-04-13 23:23 UTC, ChungusGamer666 requested changes
Almost perfect, please address the fails

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"cenat": "Demon",
uncapitalize please

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"retard": "fool nimrod",
r3tard3d = foolish
r3tard = nimrod

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"fazbear": "fae",
should be dire bear instead, it's better

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"cunny": "mechery",
lechery, not mechery

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"griddy": "charm",
fits better if changed to "gallop"

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"fapping": "self abuse",
self abusING

2024-04-13 23:23 UTC, ChungusGamer666 commented on strings/accent_universal.json
> +		"yap": "prattle",
yapping = prattling

2024-04-13 23:27 UTC, TopHatPenguin commented on strings/accent_universal.json
> -		"satan": "zizo",
Should probably keep satan as zizo

2024-04-13 23:29 UTC, JTGSZ commented on strings/accent_universal.json
> -		"lantern": "lamptern",
prob don't want to remove lantern - lamptern since its an actual item bro

2024-04-13 23:30 UTC, armorheart commented on strings/accent_universal.json
> -		"lantern": "lamptern",
Added it back,. Thanks!

2024-04-13 23:30 UTC, armorheart commented on strings/accent_universal.json
> +		"cenat": "Demon",
Fixed

2024-04-13 23:31 UTC, JTGSZ commented on strings/accent_universal.json
> -		"satan": "zizo",
also he correct too zizo is a v prevalent thing

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> +		"retard": "fool nimrod",
Fixed

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> +		"fazbear": "fae",
Fixed

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> +		"cunny": "mechery",
Fixed

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> +		"griddy": "charm",
Fixed

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> +		"fapping": "self abuse",
Fixed

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> +		"yap": "prattle",
Fixed

2024-04-13 23:31 UTC, armorheart commented on strings/accent_universal.json
> -		"satan": "zizo",
re-added as described

2024-04-13 23:33 UTC, JTGSZ commented on strings/accent_universal.json
> -		"satan": "zizo",
also since we here replacin satan with zizo, could also auto-translate lucifer to zizo

2024-04-13 23:41 UTC, TopHatPenguin commented
At some point it should be decided upon if the server should carry on pick and choosing from both old English and middle English, or simply choose to to go fully into one.

2024-04-13 23:43 UTC, armorheart commented on strings/accent_universal.json
> -		"satan": "zizo",
Ok. Gonna hit it with another push

2024-04-14 00:30 UTC, merged

2024-04-14 03:11 UTC, dessysalta commented
This changes "from" to "truthfullyom".