The Soup Update
Blackstone-SS13/BLACKSTONE pull request #77
Opened 2024-04-15 00:00 UTC by BlueMemesauce

basically you put anything in the pot and it turns it directly into nutriment with a small bonus
its meant for cooking vegetables and raw meat
its like this https://en.wikipedia.org/wiki/Pottage

also you can boil gross water to make it normal water again

i also added butter biscuit since we already had biscuit and butter so it makes sense

and lastly i added a cookbook to help you with the new soup and also cooking flour which can get pretty confusing with all the steps

2024-04-15 00:02 UTC, BlueMemesauce commented
oh yea i gotta add the book and pot to the map idk how to do that

2024-04-15 00:59 UTC, LudwigVonChesterfield commented on code/modules/power/roguelighting.dm
> +					to_chat(user, "<span class='warning'>[attachment] isn't boiling!</span>")
there's a return missing here because of which you can still put things even if water isn't boiling. is that intentional?

2024-04-15 00:59 UTC, LudwigVonChesterfield commented on code/modules/power/roguelighting.dm
> +			if(W.type in subtypesof(/obj/item/reagent_containers/food/snacks))
```suggestion
			if(istype(W, /obj/item/reagent_containers/food/snacks))
```

2024-04-15 00:59 UTC, LudwigVonChesterfield commented on code/modules/power/roguelighting.dm
> +				if(attachment.reagents.chem_temp < 374)
consider adding a water boiling temperature define

2024-04-15 01:00 UTC, LudwigVonChesterfield commented on code/modules/power/roguelighting.dm
> +					nutrimentamount = nutrimentamount * 1.25 // small bonus for boiling it
```suggestion
					nutrimentamount *= 1.25 // small bonus for boiling it. boiling food makes more nutrients digestable
```

2024-04-15 01:00 UTC, LudwigVonChesterfield commented on code/modules/power/roguelighting.dm
> +		if(attachment.type == /obj/item/reagent_containers/glass/pot)
consider istype() here

2024-04-15 12:29 UTC, LudwigVonChesterfield commented
mapmerge fail here?

2024-04-15 13:58 UTC, TopHatPenguin commented
Will need to add the book to roguetown2 instead of oldtown as we've map swapped.

2024-04-15 18:49 UTC, JTGSZ commented
conflicts

2024-04-16 21:37 UTC, emoats18 commented
Merge conflicts!

2024-04-17 17:37 UTC, Contrabang requested changes
minor thing, also make sure the map isnt conflicted

2024-04-17 17:37 UTC, Contrabang commented on code/modules/roguetown/roguejobs/cook/recipes/breads.dm
> +		/obj/item/reagent_containers/food/snacks/butterslice= 1
```suggestion
		/obj/item/reagent_containers/food/snacks/butterslice = 1
```

2024-04-18 04:12 UTC, merged