Integrates bandits with the bounty system
Blackstone-SS13/BLACKSTONE pull request #790
Opened 2024-05-13 21:56 UTC by BlueMemesauce

## About The Pull Request

i asked the author to add it in #768 but they didnt do it

## Why It's Good For The Game

now bandits fit the system

2024-05-14 20:47 UTC, Real-MAGNUM commented
conflicting

2024-05-14 23:43 UTC, BlueMemesauce commented
btw idk if this works or not

2024-05-16 00:03 UTC, Real-MAGNUM commented
Test it locally or no testmerge.

2024-05-16 21:51 UTC, BlueMemesauce commented
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47338680/455f58c7-b7b4-4ca9-b298-6adb15831e3d)
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/47338680/739e3817-075b-4e36-b4e4-1e6104955937)

2024-05-19 05:58 UTC, zoktiik commented
On a new local branch made from remote main ef00eceba5fc0f4b907a5b68c9d2260245be49fd, I merged this PR's remote branch at 11231d27904c9e4861e0e1073316446ce2ea4de1 with it to test out of curiosity, since this PR necessarily resolves the (admittedly somewhat small) issue that comes with multiple bounty machines: two different bounties making the other one unresolveable upon being claimed. The switch to `known_people` also fixes the issue of logged-out players being immune to bounties. Nice!

However, with my admittedly imperfect testing, I found a couple issues worth investigating:
- **Bandit bounty `reward` stacks seem to have no value.** Tested by making someone a bandit midround via the Traitor Panel (which still greets them properly, including the TP, gear adding, name change prompt, bounty adding, etc.) Bounty generation and deletion for multiple bandits works, but the problem is, you're paid quite literally nothing for each head.
- **Adventurers and Pilgrims seem not just immune to, but _completely outside_ the bounty system.** From what I can tell, they cannot have bounties placed on them, and they also cannot place bounties on anyone. Both people talking, hitting each other, examining each other, doesn't seem to fix this at all. I suspect this a side effect of the switch from listing objective `client`s to the `mind`'s `known_people`.

I accomplished this through multikeying, main acc and guest acc; my main's ckey was made `Host`, and my guest was `!localhost!` thru DD, both adminned of course. I deleted all test dummy objects I saw. Just good old `/mob/living/carbon/human` remained.

2024-05-19 09:44 UTC, ChungusGamer666 requested changes
mostly good stuff but the hanging refs thing got me worried ngl

2024-05-19 09:44 UTC, ChungusGamer666 commented on code/datums/mind.dm
> +			M.known_people[H]["FAGE"] = H.age
this will most likely cause hard dels due to hanging references in mind, there has to be a better way to do this

2024-05-19 09:44 UTC, ChungusGamer666 commented on code/datums/mind.dm
> +			M.known_people[H] = null
huh? shouldn't it just remove H from the list? This seems stupid as hell

2024-05-19 19:22 UTC, BlueMemesauce commented
> On a new local branch made from remote main [ef00ece](https://github.com/Blackstone-SS13/BLACKSTONE/commit/ef00eceba5fc0f4b907a5b68c9d2260245be49fd), I merged this PR's remote branch at [11231d2](https://github.com/Blackstone-SS13/BLACKSTONE/commit/11231d27904c9e4861e0e1073316446ce2ea4de1) with it to test out of curiosity, since this PR necessarily resolves the (admittedly somewhat small) issue that comes with multiple bounty machines: two different bounties on the same person making the other one unresolveable upon being claimed. The switch to `known_people` also fixes the issue of logged-out players being immune to bounties. Nice!
> 
> However, with my admittedly inexhaustive testing (given the time I put into it), I found a couple issues worth investigating:
> 
>     * **Bandit bounty `reward` cash stacks seem to have no value.** Tested by making someone a bandit midround via the Traitor Panel (which still greets them properly, including the TP, gear adding, name change prompt, bounty adding, etc.) Bounty generation and deletion for multiple bandits works, but the problem is, you're paid quite literally nothing for each head. The coin stacks are worth a whopping 0 mammon, including when they're put in SHYLOCK.
> 
>     * **Adventurers and Pilgrims seem not just immune to, but _completely outside_ the bounty system.** From what I can tell, they cannot have bounties placed on them, and they also cannot place bounties on anyone. Both people talking, hitting each other, examining each other, doesn't seem to fix this at all. I suspect this a side effect of the switch from listing objective `client`s to the `mind`'s `known_people`. I tested masks, but they seemed to have nothing to do with it; townspeople, mercenaries, and other non-migrants automatically know each other from the moment each of them spawn.
> 
> 
> I accomplished this through multikeying, main acc and guest acc; my main's ckey was made `Host`, and my guest was `!localhost!` thru DD, both adminned of course. I deleted all test dummy objects I saw. Just good old `/mob/living/carbon/human` remained.

Tbh idk why the reward thing isn't working
But I'll make it where if you examine someone it gets added to your known people

2024-05-19 20:49 UTC, zoktiik commented
> But I'll make it where if you examine someone it gets added to your known people

If you could take this just a bit further, and make sure it logs that real.name in known_people for use with the Excidium, that would be excellent. Because as things are currently, people that you know from before, but are Unknown *currently*, will also appear Unknown in the list. Going through with placing the bounty will also make the Excidium hunger for the head of Unknown. If you somehow manage to brute-force it by shoving the whole server's supply of named heads in there, good on you, but generally this behavior makes for bad bounties and should not be allowed to happen.

Also, with this behavior, do double-check that adding people to the list by shift-clicking them doesn't work if they are currently Unknown. 

(Writing this, I can foresee some real bastards abusing this big time; face hiding is going to need a real crackdown IC, lest the rogue horde get away with triple murder and yet escape a price on their heads. The following is very much out-of-scope for this PR, but maybe I should put in a request for some sort of system that auto-bounties non-antag serial killers of 3+ murders or so, whether or not this is practically doable.)

2024-05-19 22:32 UTC, BlueMemesauce commented
yea i just reverted it to the old system of storing their real_name

2024-05-24 23:33 UTC, BlueMemesauce commented
theres another bug with the bounty system where it gives you your money in a stack of coins but this should be impossible if you go over a stack of 20 since you cant normaly get that much, idk how to fix that tho unless it just splits it into stacks of 20 and gives you a fuck ton of stacks which is annoying or maybe it gives you change

2024-05-29 01:16 UTC, ChungusGamer666 commented
yea

2024-05-29 01:16 UTC, merged