giga slop pr mk7
Blackstone-SS13/BLACKSTONE pull request #813
Opened 2024-05-14 20:47 UTC by JTGSZ

IF TESTMERGING BE ON TO MONITOR THINGS
number 7 (so its lucky this time)

rewrites a ton of the triumph shit
adds triumph buy menu
merges pilgrim and adventurers into their complete hobo form
gives them a brand new selection menu w extra options
retypes beggar typepaths to beggar typepaths as im now using vagrants as a name
swaps category bools to bitflags on classes
fixes the fullscreen overlays being fucked on layers for some reason (idk happened recently)

2024-05-15 15:02 UTC, Knightfall5 commented
https://cdn.discordapp.com/attachments/1225593965643042817/1240312797745647668/image.png?ex=66461ace&is=6644c94e&hm=e0a295efe60186014af0f868aba731247a2233e4b0034400f3e4d92d486fddc7&

https://cdn.discordapp.com/attachments/1237071216767012966/1240315143720669365/image.png?ex=66461cfe&is=6644cb7e&hm=73e5c7473b5d5de4225e03129a1d950f9d1eec51e4e6709ee4bd8419a75ff592&

RNG classes is lame and stupid, people have been saying this since the server first launched. Also shit is extremely broken, both balance wise and code wise.

2024-05-15 15:33 UTC, TheManWithNoHands commented
They where not on to monitor things

2024-05-15 16:16 UTC, Real-MAGNUM requested changes
Change these prices, and for the love of christ please change the text colors here to a unified set. Ask @Takyon69 for a pallete. 
![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/60511054/858960d8-d8ab-4e8a-9e82-c8f88f5e4602)

untestmerging

2024-05-15 16:16 UTC, Real-MAGNUM commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/misc/wipe_triumphs.dm
> +	triumph_cost = 100
```suggestion
	triumph_cost = 500
```

2024-05-15 16:16 UTC, Real-MAGNUM commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/round_effects/grenzelhoft.dm
> +	triumph_cost = 30
```suggestion
	triumph_cost = 50
```

2024-05-15 16:16 UTC, Real-MAGNUM commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/character/pick_any_class.dm
> +	triumph_cost = 10
```suggestion
	triumph_cost = 2
```

2024-05-15 17:01 UTC, K4rlox commented
adventurer class pick thing does not scale with PQ, it used to do so
i really think it should still do so

2024-05-15 17:39 UTC, Real-MAGNUM commented
> adventurer class pick thing does not scale with PQ, it used to do so i really think it should still do so

There was supposed to be a slot-purchasing functionality that permanently (per character) increased the amount of slots purchased. However, the price is 1 and it doesn't seem to even work.

2024-05-15 17:40 UTC, Real-MAGNUM commented
Stop making fucking meme PR names or I'll start closing them every time regardless of changes.

2024-05-15 21:23 UTC, JTGSZ commented
Closing this PR as I'm going to redo a lot of stuff based on feedback/new design

2024-05-15 21:23 UTC, closed without merging

2024-05-16 13:46 UTC, CVSthePharmacy commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/misc/wipe_triumphs.dm
> +	triumph_cost = 100
GO FUCK YOURSELF NO, 500 WOULD TAKE AN ACTUAL 5 FUCKING MONTHS, USE YOUR FUCKING HEAD

2024-05-16 13:47 UTC, CVSthePharmacy commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/round_effects/grenzelhoft.dm
> +	triumph_cost = 30
WAY too much for a funny gimmick

2024-05-16 14:36 UTC, assortedbeads commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/misc/wipe_triumphs.dm
> +	triumph_cost = 100
Good, erasing peoples progress shouldnt be easy

2024-05-16 14:38 UTC, assortedbeads commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/round_effects/grenzelhoft.dm
> +	triumph_cost = 30
Races have stats, its not a funny gimmick its a straight up mechanical effect
Hell it should cost more

2024-05-16 14:52 UTC, CVSthePharmacy commented on code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/misc/wipe_triumphs.dm
> +	triumph_cost = 100
> Good, erasing peoples progress shouldnt be easy

hey cocksucker, that's 5-6 months of work, i'd at most be ok with 150 or 175