Witch Hunter
Blackstone-SS13/BLACKSTONE pull request #839
Opened 2024-05-15 21:55 UTC by SELFHELL

## About The Pull Request

Adds Witch Hunters Back,

## Why It's Good For The Game

With the current advent of people being able to FREELY choose heretical faiths.. the church needs some help in dealing with that shit

2024-05-15 23:47 UTC, ChungusGamer666 requested changes
Needs to be renamed to inquisitor, so people do not confuse them with adventurer witch hunters. Single slot, should also be forced into being a psydonian.

2024-05-15 23:48 UTC, pismorizzo commented
Good change especially cause of how rare it is to see one in a round let alone get to pick it. Please remove nosegrab trait though its pretty OP since it would mean they can just grab anyone, interrogate, then execute via strangling and they cant even fight back.

2024-05-16 00:09 UTC, Real-MAGNUM commented
> Needs to be renamed to inquisitor, so people do not confuse them with adventurer witch hunters. Single slot, should also be forced into being a psydonian.

I support this review

2024-05-16 00:37 UTC, SELFHELL commented
Reviews Adressed.

2024-05-16 00:56 UTC, ChungusGamer666 requested changes
final touch ups

2024-05-16 00:56 UTC, ChungusGamer666 commented on code/game/gamemodes/roguetown/roguetown.dm
> +	restricted_jobs = list("Acolyte", "Templar", "Priest","Adventurer","Confessor","Town Guard","Veteran","Castle Guard","Sheriff","Knight","Bog Guard","Bog Master","Witch Hunter")
Nuh uh, hes the inquisitor!

2024-05-16 00:56 UTC, ChungusGamer666 commented on code/modules/antagonists/roguetown/villain/vampirelord.dm
> +	var/list/churchjobs = list("Priest", "Priestess", "Cleric", "Acolyte", "Templar", "Churchling", "Crusader", "Witch Hunter")
ditto

2024-05-16 00:56 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/church/puritan.dm
> +	tutorial = "As a Inquisitor, the Queen has emboldened your sect to root out cultists and the cursed night beasts, using your practice of extracting involuntary 'sin confessions' as a guise to spy on
an*

2024-05-16 00:56 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/church/puritan.dm
>  	allowed_patrons = list(/datum/patron/old_god)
should be moved into the outfit so it just changes your patron automatically instead of cockblocking you in class select, maybe?

2024-05-16 00:56 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/church/puritan.dm
> +	tutorial = "As a Inquisitor, the Queen has emboldened your sect to root out cultists and the cursed night beasts, using your practice of extracting involuntary 'sin confessions' as a guise to spy on
also, still mentions witch hunter. also, for flavor, change it from "sect" to "extremist sect".

2024-05-16 01:11 UTC, SELFHELL commented
OTHER reviews dealt with

2024-05-16 01:12 UTC, merged

2024-05-16 03:16 UTC, FewOldTunes commented
You got a issue here; They spawn in the wilderness with no torch. I don't think you intended them on spawning there and I'm not sure what causes the issue either.

2024-05-16 21:37 UTC, Real-MAGNUM commented
Resolved in #852