Guard rework
Blackstone-SS13/BLACKSTONE pull request #858
Opened 2024-05-16 12:13 UTC by emoats18

Reworks the guards to make them more akin to a professional garrison.

Changes veteran into the Captain of the Guard.

Gives guards better equipment and makes their loadouts make more sense.

![castleguard](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/f543a814-eb68-4b15-8f35-05321a908c26)
![castleguard](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/f543a814-eb68-4b15-8f35-05321a908c26)
![castleguard](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/f543a814-eb68-4b15-8f35-05321a908c26)
![castleguard1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/57344172-a76a-4ff7-b028-2055870f4954)
![castleguard1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/57344172-a76a-4ff7-b028-2055870f4954)
![castleguard1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/57344172-a76a-4ff7-b028-2055870f4954)
![townguard](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/78fe6349-1e7f-4534-a7bc-c32925561e9c)
![townguard](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/78fe6349-1e7f-4534-a7bc-c32925561e9c)
![townguard](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/78fe6349-1e7f-4534-a7bc-c32925561e9c)
![townguard1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/0a8c465b-71bb-499f-9f11-4fcf968b9c80)
![townguard1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/0a8c465b-71bb-499f-9f11-4fcf968b9c80)
![townguard1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/0a8c465b-71bb-499f-9f11-4fcf968b9c80)
![vetaran1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/f5f73731-e1a1-4763-81ee-6f2f899b12f9)
![vetaran1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/f5f73731-e1a1-4763-81ee-6f2f899b12f9)
![vetaran1](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/f5f73731-e1a1-4763-81ee-6f2f899b12f9)
![veteran](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/9392f2d7-ccc6-4162-bb1f-386035c35487)
![veteran](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/9392f2d7-ccc6-4162-bb1f-386035c35487)
![veteran](https://github.com/Blackstone-SS13/BLACKSTONE/assets/58623582/9392f2d7-ccc6-4162-bb1f-386035c35487)

2024-05-16 13:56 UTC, kacperpl1234pl commented
making guards better geared with adventurer pop nerf gona ensure 95% of rebelions will fail

2024-05-16 14:18 UTC, CVSthePharmacy commented
>gives gaurds better equipment

bro you just nerfed castle guards by giving them the shittier helmet and a CHAIN COIF instead of their GORGET, have you SEEN the different in the HP of those two?

2024-05-16 14:27 UTC, TheManWithNoHands commented
Mate, give the keep's armory some more steel equipment as well then. I mainly put iron gear in there to not give the guards access to stronger gear than what they spawn with. It's under the keep's guard quarters.


> making guards better geared with adventurer pop nerf gona ensure 95% of rebelions will fail

Good, having rebellion 95% of the time succeed whenever they happen is very unfun. In general Castle guards are kinda weak rigth now. So it will be healthy if they actually get proper gear.

2024-05-16 14:30 UTC, CVSthePharmacy commented
> Mate, give the keep's armory some more steel equipment as well then. I mainly put iron gear in there to not give the guards access to stronger gear than what they spawn with. It's under the keep's guard quarters.
> 
> > making guards better geared with adventurer pop nerf gona ensure 95% of rebelions will fail
> 
> Good, having rebellion 95% of the time succeed whenever they happen is very unfun. In general Castle guards are kinda weak rigth now. So it will be healthy if they actually get proper gear. Always feels like their just an honor guard.

I've still gotta do my rebellion speedrun when rolling knight and getting rebel leader

2024-05-16 14:31 UTC, TheManWithNoHands commented
> I've still gotta do my rebellion speedrun when rolling knight and getting rebel leader

No way knigth is able to rebel leader. You lying.

2024-05-16 14:37 UTC, TheManWithNoHands commented
> I rolled it a few weeks ago

Dayum

2024-05-16 14:38 UTC, Real-MAGNUM commented
> > > I've still gotta do my rebellion speedrun when rolling knight and getting rebel leader
> > 
> > 
> > No way knigth is able to rebel leader. You lying.
> 
> I rolled it a few weeks ago

They were disabled since then iirc.

2024-05-16 14:38 UTC, Real-MAGNUM commented
Visual distinction between castle and town is lacking
Return the helmet and gorget on the castle guard and it's a fine PR

2024-05-16 14:39 UTC, CVSthePharmacy commented
> > > > I've still gotta do my rebellion speedrun when rolling knight and getting rebel leader
> > > 
> > > 
> > > No way knigth is able to rebel leader. You lying.
> > 
> > 
> > I rolled it a few weeks ago
> 
> They were disabled since then iirc.

can you re-add them

2024-05-16 14:40 UTC, CVSthePharmacy commented
also can you give the vet a STEEL mace or a GRAND mace instead of a normal lame mace that a WOODEN STAFF can outperform?

2024-05-16 14:49 UTC, Real-MAGNUM commented on code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/axesmaces, 6, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/combat/axesmaces, 4, TRUE)
```

2024-05-16 14:53 UTC, Real-MAGNUM commented on code/modules/jobs/job_types/roguetown/garrison/veteran.dm
> +	tutorial = "War has always been a constant of your life, and you always chose the side of defense and justice. You rose up through the ranks as a guardman and you're now the head above all of them.
```suggestion
	tutorial = "War has always been a constant of your life, and you always chose the side of defense and justice. You rose up through the ranks as a guardman and you're now the head above all of them. Lead and train your men to defend the kingdom and maintain the peace. Recruit those who you believe capable of aiding the Kingdom against offenders and pushing the tides of the kingdom's battles in your favor..."
```

2024-05-16 14:56 UTC, Real-MAGNUM requested changes
Could use some balance tweaking.

2024-05-16 14:57 UTC, Real-MAGNUM commented on code/modules/jobs/job_types/roguetown/garrison/veteran.dm
> +	beltr = /obj/item/rogueweapon/mace
```suggestion
	beltr = /obj/item/rogueweapon/mace/steel
```

2024-05-16 15:08 UTC, CVSthePharmacy commented on code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/swords, 6, TRUE)
also give them 6, they are a training role

2024-05-16 21:47 UTC, BlueMemesauce commented
So why do the captain of the guard and sheriff both exist?

2024-05-16 21:58 UTC, Real-MAGNUM commented
> So why do the captain of the guard and sheriff both exist?

I think he planned to replace it with the captain of the guard. It's the same role afaik.

2024-05-16 23:57 UTC, Wintermote commented
Not a fan of turning the veteran into a captain of the guard. Should be 2 separate roles, captain of the guard is basically what the sheriff is, veteran seems more like an old guard who's been around the block, or a hired on advisor rather than the guy leading the guard.

Also the full plate near knight armor ruins the vet aesthetics, you can't even tell he has an eye patch anymore.

2024-05-17 02:06 UTC, Real-MAGNUM commented
emoney testmerged and didnt tag it

2024-05-17 02:25 UTC, BlueMemesauce commented
why dont you just get the bot that checks when prs are testmerged

2024-05-17 02:32 UTC, YosemiteYam commented
Bad PR, why are we replacing the sheriff with the bailiff? They are NOT the same thing, the bailiff is a dumb rolebloat snowflake role you introduced and no one wanted, and ingame most bailiffs don't do shit but act as a fifth wheel to all the other advisors. You WANTED them to replace the sheriff but they have failed to do so repeatedly, with many complaints directed to how the councillors/bailiffs do basically nothing/contribute nothing regularly. Instead of town guard and bogmaster answering to the jacked sheriff that is actually a good military role you're expecting them to answer to the snowflake "judge" role that never actually judges anyone. 

Secondly you're getting rid of actual flavor in the court by turning the veteran role into the captain of the guard, basically removing veteran as a thing. 

This is a pretty big change disguised as a castle guard rework and should've been discussed more in depth before being test merged.

2024-05-17 10:05 UTC, BadAtThisGame302 commented
Now with the role Captain of the Guard, I don't think the name Sheriff fits if he is meant to be above the Captain, perhaps renaming that to like Marshal would be better? Not to mention that he can now spend time in the Court with the King advising him while the Captain keeps the Guard in check.

It can just add Court RP and more Councilmen to give advice to the King instead of everyone running off.

The Bailiff should be removed since now the Sheriff/Marshal can do his job while the Captain leads the Guard. 

Councillors can stick around and purely act as the Kings and his advisors councilmen, they just are minor nobles that have no authority except for commanding the Kings respect and their voices being heeded by him or the Hand/Steward/Sheriff etc.

2024-05-17 10:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/garrison/veteran.dm
> +	tutorial = "War has always been a constant of your life, and you always chose the side of defense and justice. You rose up through the ranks as a guardman and you're now the head above all of them.
One Kingdom is capitalized while the other kingdom isn't. Should keep it the same. (Also perhaps remove the 2 extra dots.

2024-05-17 11:43 UTC, wow50000 commented
could you bring back the old helmets though they are cool as hell ?

2024-05-17 12:04 UTC, CVSthePharmacy commented
bring back the old castle guard helmets they were cool and give them gorgets, other than that this is okayish only because of captain

2024-05-17 12:05 UTC, CVSthePharmacy commented
> Not a fan of turning the veteran into a captain of the guard. Should be 2 separate roles, captain of the guard is basically what the sheriff is, veteran seems more like an old guard who's been around the block, or a hired on advisor rather than the guy leading the guard.
> 
> Also the full plate near knight armor ruins the vet aesthetics, you can't even tell he has an eye patch anymore.
> 
> In fact, this is really just removing veteran outright as a job, not changing it.

it's half plate, clerics get it, so shush

2024-05-17 12:19 UTC, Wirpy commented
I like the equipment changes beyond the neck and helmet. 

I might be wrong but the helmet you've changed to in this pr is iron isn't it? Im fairly confident it is but I might be wrong. 

I'd also argue that a gorget is preferable to a chain coif but that might be personal preference.  Otherwise its nice and feels more professiona lto finally have chainmail underneath roundstart lol and stuff.

2024-05-17 16:09 UTC, closed without merging