given_skills added to classes
Blackstone-SS13/BLACKSTONE pull request #929
Opened 2024-05-19 16:05 UTC by ShadowLeaderJordanzo

## About The Pull Request

an attempt to be able to find a class's skills
tested and it works w/ rouge, kinda new to code base but im assuming we can tell what job/class somebody is? given thats the case, /type:: can call given_skills or stats_given if not i can try and add a text ref to the class they are

the idea: add given_skills and stats_given to the advclass datum / perhaps to job as well, not sure how jobs tie into this codebase yet
use these lists as both a ref and a way to apply stats/skills

the dream: easier to adjust skills/stats
capable of finding skills/stats of a class 

## Why It's Good For The Game

makes code life easier ig, i seen [this](https://github.com/Blackstone-SS13/BLACKSTONE/issues/699) and decided to take a shot at it.
in the long run it'll b a lot of replacing chunks of code which may b easy with a regex or something

2024-05-23 01:37 UTC, ChungusGamer666 requested changes
most impressive, and also most demented, pr made by a random contributor so fad

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
> +		"/datum/skill/combat/polearms" = 3, \
should not be strings, typepaths are perfectly valid as keys in assoc lists

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/datums/mind.dm
> +/datum/mind/proc/assign_experiences(list/Skills, silent, option)
use snakecase, Skills should not be capitalized

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/modules/mob/living/stats.dm
> +	if(!stat) return
never do evil inline code xir

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/modules/mob/living/stats.dm
>  /mob/living/proc/change_stat(stat, amt, index)
ingenious compression of a very evil proc, good job

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/modules/mob/living/stats.dm
> +#define STATTOVAR list("strength" = "STR", "perception" = "PER", "intelligence" = "INT", \
this define is kind of demonic and shouls probably just be a static list inside get_stat_var

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
> +			H.mind.assign_experiences(/datum/advclass/sfighter::stat_changes, TRUE, "Stats")
oh look its the funny new operator!


...does it even work with lists? i know for a fact initial() refuses to work with lists

2024-05-23 01:37 UTC, ChungusGamer666 commented on code/datums/mind.dm
> +	var/list/values = splittext(text, ",")
this is demonic, just use a normal ass list instead of this evil ass string manipulation
if this causes problems with the fancy new byond operator... just rawdog the list

2024-05-23 01:59 UTC, ShadowLeaderJordanzo commented on code/modules/mob/living/stats.dm
>  /mob/living/proc/change_stat(stat, amt, index)
🎈

2024-05-23 02:00 UTC, ShadowLeaderJordanzo commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
> +			H.mind.assign_experiences(/datum/advclass/sfighter::stat_changes, TRUE, "Stats")
on children yes, on parent it throws a runtime

`
/datum/test
	var/list/given_skills = list()

/datum/test/child
	given_skills = list("blah" =1 , "halb" = 2)

/mob/verb/test()
	world<<jointext(/datum/test/child::given_skills, " , ")
`

does result in: blah , halb

2024-05-23 02:06 UTC, ShadowLeaderJordanzo commented on code/datums/mind.dm
> +	var/list/values = splittext(text, ",")
im just autistic, tbh, didnt realize types can be keys in assoc lists

2024-05-23 04:40 UTC, ShadowLeaderJordanzo commented
all other jobs/classes have to b updated. ill prob get around to it this weekend if this all checks

2024-05-24 07:33 UTC, ChungusGamer666 commented on code/datums/mind.dm
> +				current.change_stat(path, numValue)
uncapitalize if possible

2024-05-25 04:28 UTC, ChungusGamer666 commented
fix conflicts and this should be good to testmerge

2024-05-25 04:32 UTC, ShadowLeaderJordanzo commented
should b good

2024-05-27 04:35 UTC, ChungusGamer666 commented
testmerging this

2024-05-29 01:34 UTC, ChungusGamer666 commented
epic merge conflicts wtf

2026-05-07 04:39 UTC, closed without merging