Added new adventurer class Cyclops, only for human/dwarf men with one eye
Blackstone-SS13/BLACKSTONE pull request #97
Opened 2024-04-15 14:01 UTC by Hmeister-real

First time, new to ss13 coding just felt like trying my hand at it, i have done it for ss14 though. Uses #73 as a base, without that wouldn't have been inspired to try doing this. Originally this was locked to just dwards but decided to open it to humens as well. (yes this is the demoman) 

I need help locking it to people with the missing eye flaw, can't figure out how. Also i want to replace the wine in their bag with normal booze, but i haven't found out how to either. Also someone let me know if there are more bombs than just fire bombs. When thats done il take PR out of draft

2024-04-15 14:03 UTC, LudwigVonChesterfield commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +  backl = /obj/item/storage/backpack/rogue/backpack
identation problem. does this even compile?

2024-04-15 14:04 UTC, LudwigVonChesterfield commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +  H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
there are multiple identation problems. enable seeing whitespace as I believe there's either spaces used for formatting here instead of tabs or ? ???

2024-04-15 15:24 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +  H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
i uh, copy and pasted some stuff. il go through this and cleanup now

2024-04-15 15:30 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +  H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
also i was orignally doing this on a portable chromebook using web git, so i didn't see the extra tab presses or lack there of originally

2024-04-15 21:31 UTC, BlueMemesauce requested changes

2024-04-16 05:41 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	if(charflaw in allowed_flaws)
uh, can you explain this further?

2024-04-16 14:39 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	if(charflaw in allowed_flaws)
add it here
https://github.com/Blackstone-SS13/BLACKSTONE/blob/8e4bf65c35895918d705e8bf5f6c8dcf8fd36f5a/code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm#L51-L72

2024-04-16 14:39 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	"Humen",
```suggestion
```

2024-04-16 15:50 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	if(charflaw in allowed_flaws)
> add it here
> 
> https://github.com/Blackstone-SS13/BLACKSTONE/blob/8e4bf65c35895918d705e8bf5f6c8dcf8fd36f5a/code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm#L51-L72

add it, or move it

2024-04-16 15:55 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	if(charflaw in allowed_flaws)
done, i think

2024-04-16 15:57 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
> +			if(charflaw in allowed_flaws)
```suggestion
			if(H.charflaw in A.allowed_flaws)
```

2024-04-16 16:04 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +
```suggestion

```

2024-04-16 16:07 UTC, BlueMemesauce commented
Add
```
var/list/allowed_flaws = ALL_FLAWS_LIST
```
https://github.com/Blackstone-SS13/BLACKSTONE/blob/8e4bf65c35895918d705e8bf5f6c8dcf8fd36f5a/code/modules/jobs/job_types/roguetown/adventurer/types/_advclass.dm#L1-L15

2024-04-16 17:07 UTC, Cdey78 commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
This is absurd for an adventurer, only the sheriff compares to this high of a skill. should probably be 3 maximum. Though, frankly, I don't understand any of the stat or skill choices here.

2024-04-16 17:09 UTC, Cdey78 commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
I would not recommend using the website editor at all. We don't need to merge anything that's untested or nonfunctional, even the standard DM editor is better. 

Can you compile and run it locally?

2024-04-16 18:10 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
Well, as i said a lot of it is based off of the demoman. but yeah swords probably shouldnt be this high, il tone it down

2024-04-16 18:15 UTC, Hmeister-real commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
> Can you compile and run it locally?

I can't, i have very little experience with ss13 side of coding, but i have been told that it will work, and the stuff being added isn't mechanically taxing, it's just a new adv class type, so it doesn't exactly need much testing since it's mostly stats

2024-04-16 18:18 UTC, LudwigVonChesterfield commented on code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
> +			if(H.charflaw in A.allowed_flaws)
right now you're excluding classes based on whether the flaw is in the allowed list. this means that only people without a missing eye can become a cyclops. but it also means that no other class can be chosen. maybe you meant
```suggestion
			if(!(H.charflaw in A.allowed_flaws))
```

2024-04-16 18:28 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
> +					continue
indentation error
```suggestion
			continue
```

2024-04-16 18:34 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
Running it locally is pretty easy
1. install dm visuals studio code extension pack
2. open repo folder in visual studio code 
3. press ctrl shift b and build dm
4. open dream daemon and run the dmb file

2024-04-16 19:03 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
> +			continue
its hard to format, you removed too many
```suggestion
				continue
```

2024-04-16 22:22 UTC, BlueMemesauce commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	backpack_contents = list(/obj/item/bomb = 3, /obj/item/flint = 1 /obj/item/reagent_containers/glass/bottle/rogue/wine = 2)
```suggestion
	backpack_contents = list(/obj/item/bomb = 3, /obj/item/flint = 1, /obj/item/reagent_containers/glass/bottle/rogue/wine = 2,)
```

2024-04-17 03:27 UTC, Cdey78 commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	backpack_contents = list(/obj/item/bomb = 3, /obj/item/flint = 1 /obj/item/reagent_containers/glass/bottle/rogue/wine = 2)
No comma necessary after wine, only after flint.

2024-04-17 03:29 UTC, Cdey78 commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/cyclops.dm
> +	H.mind.adjust_skillrank(/datum/skill/combat/swords, 5, TRUE)
VS is nice but not required. We don't use build.bat files here. Even then, just using the F5 hotkey will automatically host a server locally for yourself and connect you to it.

BYOND comes with a built-in code editor, you have this unless you don't have BYOND installed. Attempting to open a .dme file should automaticaly open the DM editing program. From here, you can go to the top left > build > compile.
DO NOT USE CLEAN COMPILE.

2024-04-17 03:32 UTC, SELFHELL commented
My genuine advice to you is to just copy and paste another loadout in the future and swap out items. Helps stop silly formatting issues that are usually caused by typing it out by hand

2024-04-17 05:02 UTC, Hmeister-real commented
> My genuine advice to you is to just copy and paste another loadout in the future and swap out items. Helps stop silly formatting issues that are usually caused by typing it out by hand

i did, it's just that for the flaw code is completely new and i had nothing to copy it from, i originally copied the dwarf warrior PR since i originally wanted cyclops to be dwarf only

2024-04-17 08:49 UTC, Hmeister-real commented
Closing this because 20 commit bloat

2024-04-17 08:49 UTC, closed without merging